[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ISP-SDK = "0.1.0-alpha.0.2"
candid = "0.7.16"
tokio = { version = "1", features = ["full"] }